const assert = require('node:assert/strict');
const M = require('./hesap.js');
const g = { satislar: Array(12).fill(100000), maliyetYuzde: 60, sabitGider: 20000, acilisNakit: 100000, tahsilatAy: 2, stokAy: 1, odemeAy: 0 };
const r = M.hesapla(g);
assert.equal(r.kar, 240000);
assert.equal(r.nakitDongusuGun, 90);
assert.equal(r.hazirlik, 60000);
assert.equal(r.alacak, 200000);
assert.equal(r.borc, 0);
assert.equal(r.aylar[0].tahsilat, 0);
assert.equal(r.aylar[2].tahsilat, 100000);
assert.equal(r.iz[0].nakit, 40000);
assert.equal(r.gereken, 220000);
assert.equal(r.ilave, 120000);
assert.equal(r.ilkAcik, 1);
assert.equal(r.kapanis, 140000);
const a = M.hesapla({ ...g, tahsilatAy: 0, stokAy: 0, odemeAy: 0 });
assert.equal(a.gereken, 0);
assert.equal(a.kapanis, 340000);
const b = M.hesapla({ ...g, acilisNakit: 0, odemeAy: 4 });
assert.equal(b.hazirlik, 0);
assert.equal(b.borc, 180000);
assert.equal(b.ilkAcik, 1);
const s = M.senaryolar(g);
assert.equal(s.senaryolar.length, 4);
assert.ok(s.senaryolar[1].gereken >= s.plan.gereken);
assert.ok(s.senaryolar[2].kar < s.plan.kar);
for (const bad of [{ ...g, satislar: [1] }, { ...g, tahsilatAy: 1.5 }, { ...g, maliyetYuzde: -1 }, { ...g, satislar: Array(12).fill(NaN) }]) assert.throws(() => M.hesapla(bad));
console.log('Nakit Köprüsü hesap doğrulamaları geçti.');
